//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;

[assembly: EdmSchema()]
namespace WAQSTemplate
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WAQSModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WAQSModelContainer object using the connection string found in the 'WAQSModelContainer' section of the application configuration file.
        /// </summary>
        public WAQSModelContainer() : base("name=WAQSModelContainer", "WAQSModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WAQSModelContainer object.
        /// </summary>
        public WAQSModelContainer(string connectionString) : base(connectionString, "WAQSModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WAQSModelContainer object.
        /// </summary>
        public WAQSModelContainer(EntityConnection connection) : base(connection, "WAQSModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
